/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./src/packages/shared/components/layout/AppDrawer.vue')['default']
    AppHeader: typeof import('./src/packages/shared/components/layout/AppHeader.vue')['default']
    PagingComp: typeof import('./src/packages/shared/components/global/PagingComp.vue')['default']
    PopOver: typeof import('./src/packages/shared/components/global/PopOver.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
