/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./packages/shared/components/layout/default/AppDrawer.vue')['default']
    AppHeader: typeof import('./packages/shared/components/layout/default/AppHeader.vue')['default']
    CLGrid: typeof import('./packages/shared/components/global/CLGrid.vue')['default']
    DataGrid: typeof import('./packages/shared/components/global/DataGrid.vue')['default']
    GMGrid: typeof import('./packages/shared/components/global/GMGrid.vue')['default']
    PagingComp: typeof import('./packages/shared/components/global/PagingComp.vue')['default']
    PopOver: typeof import('./packages/shared/components/global/PopOver.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VuetifyTable: typeof import('./packages/shared/components/global/serverTable/VuetifyTable.vue')['default']
  }
}
